name: 'Install Deps'
description: 'Install dependencies and set NX cache'
outputs:
  nx-cache-hit:
    description: 'Whether the nx cache was hit or not'
    value: ${{ steps.nx_cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - uses: volta-cli/action@v4
      with:
        package-json-path: '${{ github.workspace }}/package.json'

    - name: Use NX cache if available
      id: nx_cache
      uses: actions/cache@v3
      with:
        path: tmp/cache
        key: ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('libs/**/src/**') }}-${{ hashFiles('apps/**/src/**') }}
        restore-keys: |
          ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('libs/**/src/**') }}
          ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}
          ${{ runner.os }}-nx

    - name: Use the package manager cache if available
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: npm ci
