#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Stashing uncommitted changes..."
old_stash=$(git rev-parse -q --verify refs/stash)
git stash -q
new_stash=$(git rev-parse -q --verify refs/stash)

popStash() {
  if [ "$old_stash" != "$new_stash" ]; then
    git stash pop -q
    echo "Stashed changes popped."
  fi

  return 0;
}

echo "Running pre-push hook..."
echo "Checking code formatting..."
npx nx format:check || ( \
  echo "Code formatting failed, run 'npx nx format:write' to fix it." && \
  popStash && \
  exit 1 \
)

echo "Code formatting check completed."

echo "Checking affected projects lint, test and build targets..."
npx nx affected -t lint test build || ( \
  echo "Affected projects lint, test and build targets failed." && \
  popStash && \
  exit 1 \
)

echo "Affected projects lint, test and build targets completed successfully."
popStash
echo "Pre-push hook completed successfully."
