name: 'CI/CD'
on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main

jobs:
  prep_cache:
    name: '[Nx] Prepare Cache'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare
        id: prep
        uses: ./.github/actions/install-deps

      - name: Run all
        if: steps.prep.outputs.nx-cache-hit == 'false'
        run: npx nx run-many --targets=lint,test,build --all --configuration=ci --parallel --maxParallel=3
        env:
          NX_REJECT_UNKNOWN_LOCAL_CACHE: 0

  test:
    name: '[Nx] Test All'
    runs-on: ubuntu-latest
    needs: prep_cache
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all branches and commits so that Nx affected has a base to compare against

      - name: Prepare
        uses: ./.github/actions/install-deps

      - name: Test
        run: npx nx run-many --targets=test --all --configuration=ci --parallel --maxParallel=3
        env:
          NX_REJECT_UNKNOWN_LOCAL_CACHE: 0

      - name: Codecov
        uses: codecov/codecov-action@v4.4.0
        if: hashFiles('coverage/**/*') != ''
        with:
          directory: coverage
          token: ${{ secrets.CODECOV_TOKEN }} # required
          fail_ci_if_error: true
          verbose: true

  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    needs: prep_cache
    if: github.event_name == 'push'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/install-deps

      - name: Build App
        run: |
          npx nx run hpb-client:build:production
        env:
          NX_REJECT_UNKNOWN_LOCAL_CACHE: 0

      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_PLANT_014CF8603 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/dist/apps/hpb-client' # App source code path
          skip_app_build: true
          api_location: '' # Api source code path - optional
          ###### End of Repository/Build Configurations ######
