name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_affected:
    name: '[Nx] Run Affected'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all branches and commits so that Nx affected has a base to compare against

      - name: Prepare
        uses: ./.github/actions/install-deps

      - name: 'Run lint,test,build on affected'
        run: npx nx affected --target=lint,test,build --parallel --maxParallel=3 --base=origin/main --head=HEAD

  test:
    name: '[Nx] Test All'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all branches and commits so that Nx affected has a base to compare against

      - name: Prepare
        uses: ./.github/actions/install-deps

      - name: Test
        run: npx nx run-many --targets=test --all --configuration=ci --parallel --maxParallel=3

      - name: Codecov
        uses: codecov/codecov-action@v3.1.4
        if: hashFiles('coverage/**/*') != ''
        with:
          fail_ci_if_error: true
          verbose: true
