name: CI
on:
  push:
    branches:
      - main
      - renovate-github/**
  pull_request:
    branches:
      - main

jobs:
  run_affected:
    name: '[Nx] Run Affected'
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: ./.github/actions/install-deps

      - name: 'Run lint,test,build on affected'
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: lint,test,build
          affected: true

  test:
    name: '[Nx] Test All'
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: ./.github/actions/install-deps

      - name: Test
        run: npx nx run-many --targets=test --all --configuration=ci --parallel --maxParallel=3

      - name: Codecov
        uses: codecov/codecov-action@v3.1.4
        if: hashFiles('coverage/**/*') != ''
        with:
          fail_ci_if_error: true
          verbose: true
